Instaapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from user import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from user import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'insta/',include('insta.urls')),
    url(r'',include('insta.urls')),
    url(r'^$',user_views.register,name='register'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'profile/$', user_views.profile, name='profile'),
    url(r'^friendship/', include('friendship.urls')),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
    url(r'^accounts/', include('registration.backends.simple.urls')),

]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

insta/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import PostListView,PostCreateView,PostUpdateView
urlpatterns=[
    url(r'^$',PostListView.as_view(),name='home'),
    url(r'^post/new/$', PostCreateView.as_view(), name='post-create'),
    url(r'^post/<int:pk>/update$', PostUpdateView.as_view(), name='post-update'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^comment/(?P<post_id>\d+)', views.add_comment, name='comment'),
    url(r'^prof/(?P<username>[-_\w.]+)/$', views.profile, name='prof'),
    url(r'^profile/(?P<username>[-_\w.]+)/followers/$', views.followers, name='followers'),
    url(r'^profile/(?P<username>[-_\w.]+)/following/$', views.following, name='following'),
    url(r'^profile/(?P<username>[-_\w.]+)/$', views.profile, name='profile'),
    url(r'^post/(?P<pk>\d+)/$', views.post, name='post'),
    url(r'^profile/(?P<username>[-_\w.]+)/edit/', views.profile_settings, name='profile_settings'),
    url(r'^search/',views.search_results, name='search_results'),

    url(r'^post/(?P<pk>\d+)/likes/$', views.likes, name='likes'),

]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

insta/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from user.models import Profile
# Create your models here.
class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE,related_name="yg")
    title = models.CharField(max_length=60, null=True)
    time_created = models.DateTimeField(auto_now=True, auto_now_add=False)
    likes = models.IntegerField(default=0, null=True)
    caption = models.CharField(max_length=140, default="")
    user_profile = models.ForeignKey(Profile, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('home')
    def save_image(self):
        self.save()

    @classmethod
    def retrieve_all(cls):
        all_objects = Image.objects.all()
        for item in all_objects:
            return item;

    @classmethod
    def get_image_by_id(cls,incoming_id):
        image_result = cls.objects.get(id=incoming_id)
        return image_result


    @classmethod
    def update_image(cls,current_value,new_value):
        fetched_object = Image.objects.filter(author=current_value).update(author=new_value)
        return fetched_object
class Comment(models.Model):
    post = models.ForeignKey('Image', null=True)
    user = models.ForeignKey(User)
    comment = models.CharField(max_length=100)
    posted_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment
class Like(models.Model):
    post = models.ForeignKey('Image')
    user = models.ForeignKey(User)

    class Meta:
        unique_together = ("post", "user")

    def __str__(self):
        return 'Like: ' + self.user.username + ' ' + self.post.title

class Followers(models.Model):
    user = models.CharField(max_length=20,default='')
    Follower = models.CharField(max_length=20,default='')

insta/forms.py
from django import forms
from .models import Image,Comment
from user.models import Profile

class PhotoUploadModelForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = [ 'title','image','caption']
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_path', 'bio']

insta/views.py
from django.shortcuts import render, redirect,get_object_or_404,reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
)
from annoying.decorators import ajax_request
from .forms import PhotoUploadModelForm,CommentForm,ProfileEditForm
from friendship.models import Friend, Follow, Block
from django.contrib.auth.decorators import login_required

from .models import Image,Comment
from user.models import User,Profile


def home(request):
    posts= Image.objects.all(),
    commentform= CommentForm()

    return render(request, 'index.html', locals())

class PostListView(LoginRequiredMixin,ListView):
    model=Image
    template_name= 'instagram/image_list.html'
    context_object_name = 'posts'
    ordering = ['-time_created']

class PostCreateView(LoginRequiredMixin,CreateView):
    form_class = PhotoUploadModelForm
    template_name = 'insta/image_upload.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.user_profile= self.request.user.profile
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Image
    fields = ['title', 'content']

class create_comment(CreateView):
    model=Comment
    template_name= 'instagram/image_list.html'

    context_object_name = 'comments'
    ordering = ['-posted_on']

def signout(request):
    logout(request)
    return redirect('login')



def add_comment(request,post_id):
    post = get_object_or_404(Image, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
    return redirect('home')


@login_required(login_url='/accounts/login/')
def search_results(request):
    if 'searchItem' in request.GET and request.GET["searchItem"]:
        search_term = request.GET.get("searchItem")
        searched_user = Profile.search_by_username(search_term)
        message = f"{search_term}"
        context = {
            'message': message,
            'searched_user': searched_user
        }
        return render(request, 'search.html', context)

    else:
        message = "You haven't searched for any term"
        return render(request, 'index.html',{"message":message})

@login_required(login_url='/accounts/login/')
def profile(request, username):
    user = User.objects.get(username=username)
    if not user:
        return redirect('home')

    profile = Profile.objects.get(user=user)
    context = {
        'username': username,
        'user': user,
        'profile': profile
    }
    print(profile.user.username)
    print(profile.image)
    return render(request, 'instagram/profile.html', context)
@login_required(login_url='/accounts/login/')
def post(request, pk):
    post = Image.objects.get(pk=pk)
    try:
        like = Like.objects.get(post=post, user=request.user)
        liked = 1
    except:
        like = None
        liked = 0

    context = {
        'post': post,
        'liked': liked
    }
    return render(request, 'insta/post.html', context)


def likes(request, pk):

    post = Image.objects.get(pk=pk)
    profiles = Like.objects.filter(post=post)

    context = {
        'header': 'Likes',
        'profiles': profiles
    }
    return render(request, 'insta/follow_list.html', context)


def followers(request, username):
    user = User.objects.get(username=username)
    user_profile = Profile.objects.get(user=user)
    profiles = user_profile.followers.all

    context = {
        'header': 'Followers',
        'profiles': profiles,
    }

    return render(request, 'insta/follow_list.html', context)

@login_required(login_url='/accounts/login/')
def following(request, username):
    user = User.objects.get(username=username)
    user_profile = Profile.objects.get(user=user)
    profiles = user_profile.following.all

    context = {
        'header': 'Following',
        'profiles': profiles
    }
    return render(request, 'insta/follow_list.html', context)
@login_required(login_url='/accounts/login/')
def profile_settings(request, username):
    user = User.objects.get(username=username)
    if request.user != user:
        return redirect('index')

    if request.method == 'POST':
        print(request.POST)
        form = ProfileEditForm(request.POST, instance=user.profile, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('profile', kwargs={'username': user.username}))
    else:
        form = ProfileEditForm(instance=user.profile)

    context = {
        'user': user,
        'form': form
    }
    return render(request, 'instagram/profile_settings.html', context)


def follow(request,user_id):
    res = AjaxFollow(request.Get,request.user)

    context = { 'ajax_output': ajax_output()}
    return render(request,'insta/profile.html',context)

insta/templates/instagram/follow_list.html
{% extends 'base.html' %}

{% load static custom_tags %}

{% block content %}
<div class="follow__wrapper row">
  <div class="follow__heading">
    {{ header }}
  </div>
  {% for profile in profiles %}
    <div class="follow__card" id="{{ profile.pk }}">

      {% if profile.profile_path %}
        <img class="picture-circle--small" src="{{ profile.profile_path.url }}">
      {% else %}
        <img class="picture-circle--small" src="{% static 'images/profile_placeholder.jpg' %}">
      {% endif %}
      <a href="{% url 'profile' profile.user.username %}">{{ profile.user.username }}</a>

      {% if request.user.is_authenticated and profile != request.user.userprofile %}
        <div class="follow-toggle__container">
          {% is_following request.user.userprofile profile as following %}
          <button class="btn btn-primary {% if not following %}follow-user{% else %}unfollow-user{% endif %}">
            {% if not following %}
              Follow
            {% else %}
              Following
            {% endif %}
          </button>
        </div>
      {% endif %}
    </div>
  {% endfor %}
</div>
{% endblock %}

insta/templates/instagram/image_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="cards-listing">
        {% for post in posts %}
            <div class="row">
                <div class="card view-update {{ post.pk }}">
                    <div class="card__panel-head">
                        <div class="poster__info">
                            <a href="/insta/prof/{{post.user_profile.user.username}}" style="text-decoration:none; font-size: 16px; display:inline-block" class="user">

                                <img class="poster__profilepic" src="{{ post.user_profile.profile_path.url }}">
                              {{ post.author.username }}
                            </a>
                        </div>
                    </div>
                    <img class="card__main-image" src="{{ post.image.url }}">
                    <div class="card__panel-body">
                        <span class="poster__timestamp">
                            {{ post.time_created|timesince }}
                        </span>
                        <a href="#">
                          <div class="likes">
                              <span class="comment"><a class="fa fa-heart" style="color:red; font-size: 20px;" href="#"></a>
                              </span>
                          </div>
                        </a>
                        <ul class="comment-list">
                          <li class="comment-list__comment">
                            <a class="user" href="/insta/prof/{{post.user_profile.user.username}}">
                              {{ post.user_profile.user.username }}
                            </a>
                            <span class="comment">{{ post.title }}</span>

                          </li>
                          <a class="view-more"></a>
                          {% for comment in post.comment_set.all %}
                            <li class="comment-list__comment">
                              <a href="/insta/prof/{{post.user_profile.user.username}}" class="user">
                                {{ comment.user.username }}
                              </a>
                              <span class="comment">{{ comment.comment }}</span>
                            </li>
                          {% endfor %}
                        </ul>
                        {% if request.user.is_authenticated %}
                          <section class="input-row">
                            <i class="fa # submit-like" aria-hidden="true"></i>
                            <div class="comment-input-wrapper">
                                <form action="{% url 'comment' post_id=post.id %}" method="post">
                                    {% csrf_token %}
                                    <input class="add-comment" name="comment" id="comment{{post.id}}" type="text" placeholder="Add a comment...">
                </form>
                            </div>
                            <div class="hidden-data {{ post.pk }}" style="display: none;">
                              <span class="post-pk">{{ post.pk }}</span>
                            </div>
                          </section>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

insta/templates/instagram/image_upload.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create a Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" style="width: 10%; height: 10%;"type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

insta/templates/instagram/post.html
{% extends 'base.html' %}

{% load static custom_tags %}

{% block content %}
<div class="row single-post">
  <div class="single-post-card view-update {{ post.pk }}">
    <div class="header">
      <a href="{% url 'profile' post.user_profile.user.username %}">
        {% if post.user_profile.profile_pic %}
          <img class="picture-circle--medium" src="{{ post.user_profile.profile_pic.url }}">
        {% else %}
          <img class="picture-circle--medium" src="{% static 'images/profile_placeholder.jpg' %}">
        {% endif %}
        {{ post.user_profile.user.username }}
      </a>
    </div>
    <div class="image__wrapper">
      <img class="card__main-image" src="{{ post.image.url }}">
    </div>
    <div class="comments-portion">
      <div class="likes-timestamp-row">
        <div class="likes">
          <a href="{% url 'likes' post.pk %}">
            {% if post.get_number_of_likes %}
              {{ post.get_number_of_likes }} like{% if post.get_number_of_likes > 1 %}s{% endif %}
            {% endif %}
          </a>
        </div>
        <div class="timestamp">
            {{ post.posted_on|timesince }}
        </div>
      </div>
      <ul class="comment-list">
        <li class="comment-list__comment">
          <a class="user" href="{% url 'profile' post.user_profile.user.username %}">
            {{ post.user_profile.user.username }}
          </a>
          <span class="comment">{{ post.title | parse_hashtags | safe }}</span>
        </li>
        {% for comment in post.comment_set.all %}
          <li class="comment-list__comment">
            <a href="{% url 'profile' comment.user.username %}" class="user">
              {{ comment.user.username }}
            </a>
            <span class="comment">{{ comment.comment }}</span>
          </li>
        {% endfor %}
      </ul>
      {% if request.user.is_authenticated %}
        <section class="input-row">
          <i class="fa {% if liked %}fa-heart{% else %}fa-heart-o{% endif %} submit-like" aria-hidden="true"></i>
          <div class="comment-input-wrapper">
            <input class="add-comment" type="text" placeholder="Add a comment...">
          </div>
          <div class="hidden-data {{ post.pk }}" style="display: none;">
            <span class="post-pk">{{ post.pk }}</span>
          </div>
        </section>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

insta/templates/instagram/post_detail.html
{% extends "base.html" %}
{% block content %}
        <article class="media content-section" 
          <img class="rounded-circle article-img" style="
            height: 125px;
            width: 125px;
            margin-right: 20px;
            margin-bottom: 16px;
          " src="{{ object.author.profile.profile_photo.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ object.author }}</a>
              <small class="text-muted">{{ object.time_created|date:"F d, Y" }}</small>
            </div>

            <p class="article-content">{{ object.caption }}</p>
          </div>
        </article>
{% endblock content %}

insta/templates/instagram/profile.html
{% extends 'base.html' %}
{% load static custom_tags %}
{% block content %}
<style>
img {
  display: block;
}
.picture-circle{
    height: 170px;
    width: 170px;
}

</style>


<header>

	<div class="container m-0 p-o">

		<div class="profile">

			<div class="profile-image">
				{% if profile.profile_path %}
				<img class="picture-circle" src="{{ profile.profile_path.url }}" alt="">
				{% else %}
                <img class="picture-circle" src="{% static 'images/profile_placeholder.jpg' %}">
              {% endif %}
			</div>

			<div class="profile-user-settings">

				<h1 class="profile-user-name">{{ user.username }}</h1>
				{% if request.user == user %}

				<a href="{% url 'profile'  %}"><button class="btn profile-edit-btn">Edit Profile</button>
				</a>
				<a href="{% url 'post-create'  %}"><button class="btn profile-edit-btn">Share Post</button>
				</a>
				<button class="btn profile-settings-btn" aria-label="profile settings"><i class="fas fa-cog" aria-hidden="true"></i></button>

			</div>
			{% elif request.user.is_authenticated %}
			<div class="follow-toggle__container">
			  {% is_following request.user.profile profile as following %}
			  <button class="btn btn-primary {% if not following %}follow-user{% else %}unfollow-user{% endif %}" id="{{ profile.pk }}">
				{% if not following %}
				  Follow
				{% else %}
				  Following
				{% endif %}
			  </button>   {% endif %}
			<div class="profile-stats">

				<ul>
					<li><span class="profile-stat-count">{{ profile.image_set.count }}</span> posts</li>
					<li><span class="profile-stat-count">{{ profile.get_number_of_followers }}</span> followers</li>
					<li><span class="profile-stat-count">{{ profile.get_number_of_following }}</span> following</li>
				</ul>

			</div>

			<div class="profile-bio">

				<p><span class="profile-real-name">{{ user.username }}</span>{% if profile.bio %}{{ profile.bio }}{% endif %}</p>

			</div>

		</div>

	</div>

</header>

<main>

	<div class="container">

		<div class="gallery">
            {% for post in profile.image_set.all %}

			<div class="gallery-item" tabindex="0">

				<img src="{{ post.image.url }}" data-toggle="modal" data-target="#exampleModalCenter" class="gallery-image" alt="">

				<div class="gallery-item-info">

					<ul>
						<li class="gallery-item-likes"><span class="visually-hidden">Likes:</span><i class="fas fa-heart" aria-hidden="true"></i> 56</li>
						<li class="gallery-item-comments"><span class="visually-hidden">Comments:</span><i class="fas fa-comment" aria-hidden="true"></i> {{ post.image.comments.count }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>

                          <li class="gallery-item-likes"><span class="visually-hidden"></span><i class="fas fa-eye"  data-toggle="modal" data-target="#exampleModalCenter{{post.id}}" aria-hidden="true"></i> </li>

                    </ul>

				</div>

			</div>
            {% endfor %}

            {% for post in profile.image_set.all %}

            <div class="modal fade" id="exampleModalCenter{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLongTitle">{{post.title}}</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                        <img src="{{ post.image.url }}" data-toggle="modal" data-target="#exampleModalCenter" class="gallery-image" alt="">

                    </div>
                    <div class="modal-footer">
                        <h3>{{post.caption}}</h3>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
		</div>

	</div>
</main>
{% endblock %}










<header>
        <div class="profile">

          <div class="profile-image">
              {% if profile.profile_path %}
                <img class="picture-circle" src="{{ profile.profile_path.url }}">
              {% else %}
                <img class="picture-circle" src="{% static 'images/profile_placeholder.jpg' %}">
              {% endif %}

          </div>

          <div class="profile-user-settings">

            <h1 class="profile-user-name">{{ user.username }}</h1>
            {% if request.user == user %}

            <a class="edit-desktop" href="{% url 'profile_settings' user.username %}">
              <button class="btn profile-edit-btn">Edit Profile</button>
            </a>

            <button class="btn profile-settings-btn" aria-label="profile settings"><i class="fas fa-cog" aria-hidden="true"></i></button>
            <div class="options-bubbles" type="button" data-toggle="modal" data-target="#logoutModal">
              <p class="bubble"></p>
              <p class="bubble"></p>
              <p class="bubble"></p>
            </div>
          {% elif request.user.is_authenticated %}
          <div class="follow-toggle__container">
            {% is_following request.user.profile profile as following %}
            <button class="btn btn-primary {% if not following %}follow-user{% else %}unfollow-user{% endif %}" id="{{ profile.pk }}">
              {% if not following %}
                Follow
              {% else %}
                Following
              {% endif %}
            </button>   {% endif %}
          </div>
          </div>

          <div class="profile-stats">

            <ul>
              <li><span class="profile-stat-count">{{ profile.image_set.count }}</span> posts</li>
              <li><span class="profile-stat-count">{{ profile.get_number_of_followers }}</span> followers</li>
              <li><span class="profile-stat-count">{{ profile.get_number_of_following }}</span> following</li>
            </ul>

          </div>

          <div class="profile-bio">

            <p><span class="profile-real-name">{{ user.username }}</span>{% if profile.bio %}{{ profile.bio }}{% endif %}</p>

          </div>

</header>
    <main>

      <div class="container">

        <div class="gallery">
            {% for post in profile.image_set.all %}


          <div class="gallery-item" tabindex="0">
            <button type="button" data-toggle="modal" data-target="#exampleModalCenter">
                <img src="{{ post.image.url }}" class="gallery-image" alt="">
            </button>

            <div class="gallery-item-info">

              <ul>
                <li class="gallery-item-likes"><span class="visually-hidden">Likes:</span><i class="fas fa-heart" aria-hidden="true"></i> 56</li>
                <li class="gallery-item-comments"><span class="visually-hidden">Comments:</span><i class="fas fa-comment" aria-hidden="true"></i> {{ post.image.comments.count }}</li>


            </ul>

            </div>


          </div>
          {% endfor %}
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
            Launch demo modal
          </button>  km,./
  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
	  <div class="modal-content">
		<div class="modal-header">
		  <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
		  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		  </button>
		</div>
		<div class="modal-body">
		  ...
		</div>
		<div class="modal-footer">
		  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		  <button type="button" class="btn btn-primary">Save changes</button>
		</div>
	  </div>
	</div>
  </div>
        </div>
      </div>
    </main>

insta/templates/instagram/profile_settings.html
{% extends 'base.html' %}

{% load static custom_tags %}

{% block content %}
<style>
  .picture-circle, .picture-circle--medium, .picture-circle--small {
    border-radius: 100%;
    width: 150px;
    height: 150px; }
    .picture-circle--medium {
      width: 36px;
      height: 36px; }
    .picture-circle--small {
      width: 30px;
      height: 30px; }

  .picture-square {
    position: relative;
    background-repeat: no-repeat;
    background-position: center center;
    background-color: #fff;
    cursor: pointer; }
    .picture-square > a {
      cursor: pointer; }
    .picture-square:after {
      content: "";
      display: block;
      padding-bottom: 100%; }
    .picture-square .content {
      cursor: pointer;
      display: none;
      position: absolute;
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.3); }
    .picture-square:hover .content {
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 18px;
      color: #fff; }
      .picture-square:hover .content .fa {
        color: #fff;
        margin-right: 5px; }
        .picture-square:hover .content .fa:not(:first-of-type) {
          margin-left: 25px; }
          .profile__body > .row > .col-xs-4 {
      padding: 13px; }
  </style>
<div class="jumbotron">
<div class="row profile-settings">
  <div class="col-xs-12">
    <div class="profile-pic-name">
      {% if user.profile.profile_path %}
        <img class="picture-circle--medium" src="{{ user.profile.profile_path.url }}">
      {% else %}
        <img class="picture-circle--medium" src="{% static 'images/profile_placeholder.jpg' %}">
      {% endif %}
      <span class="username">{{ user.username }}</span>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        {{ form.profile_path.label }}
        {{ form.profile_path }}
        {{ form.profile_path.errors }}
      </div>
      <div class="form-group">
        {{ form.bio.label }}<br>
        {{ form.bio|addClass:"form-control" }}
        {{ form.bio.errors }}
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
</div>
</div>
{% endblock %}